import { useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { deleteNote, downloadNote, getMyNotes, searchNotes, uploadNote } from "../services/note.service";

function Notes() {
    const [notes, setNotes] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [searchParams] = useSearchParams(); const search = searchParams.get("search")?.trim() || "";
    const loadNotes = async () => { setLoading(true); try { const response = await getMyNotes({ limit: 50 }); setNotes(response.data.data.notes); } catch (err) { setError(err.response?.data?.message || "Could not load your notes."); } finally { setLoading(false); } };
    useEffect(() => {
        const request = search ? searchNotes({ search, limit: 50 }) : getMyNotes({ limit: 50 });
        request
            .then((response) => setNotes(response.data.data.notes))
            .catch((err) => setError(err.response?.data?.message || "Could not load your notes."))
            .finally(() => setLoading(false));
    }, [search]);
    const submit = async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); setSaving(true); setError(""); try { const response = await uploadNote(data); setNotes((items) => [response.data.data, ...items]); setOpen(false); event.currentTarget.reset(); if (!search) loadNotes(); } catch (err) { setError(err.response?.data?.message || "Could not upload the note."); } finally { setSaving(false); } };
    const remove = async (id) => { if (!window.confirm("Delete this note? This cannot be undone.")) return; try { await deleteNote(id); setNotes((items) => items.filter((note) => note._id !== id)); } catch (err) { setError(err.response?.data?.message || "Could not delete note."); } };
    const download = async (id) => { try { const response = await downloadNote(id); window.open(response.data.data.downloadUrl, "_blank", "noopener,noreferrer"); } catch (err) { setError(err.response?.data?.message || "Could not start the download."); } };
    return <div className="mx-auto max-w-6xl"><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-bold">{search ? `Search results for “${search}”` : "Notes"}</h1><p className="mt-1 text-sm text-slate-500">{search ? "Public notes matching your search." : "Your uploaded study material."}</p></div><button type="button" onClick={() => setOpen(true)} className="rounded-md bg-slate-900 px-4 py-2 text-sm font-semibold text-white hover:bg-slate-700">Upload note</button></div>{error && <p className="mb-4 rounded-md border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}
        {loading ? <p className="text-sm text-slate-500">Loading notes…</p> : notes.length === 0 ? <div className="border-y border-slate-200 py-12 text-sm text-slate-500">No notes yet. Upload a PDF to get started.</div> : <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{notes.map((note) => <article key={note._id} className="overflow-hidden rounded-lg border border-slate-200 bg-white"><div className="h-28 bg-slate-100">{note.coverImage?.url && <img src={note.coverImage.url} alt="" className="h-full w-full object-cover" />}</div><div className="p-4"><div className="flex gap-2"><h2 className="min-w-0 flex-1 truncate font-semibold">{note.title}</h2>{note.isPrivate && <span className="text-xs text-slate-500">Private</span>}</div><p className="mt-2 line-clamp-2 text-sm text-slate-600">{note.description || "No description"}</p>{note.tags?.length > 0 && <p className="mt-3 text-xs text-slate-500">{note.tags.map((tag) => `#${tag}`).join("  ")}</p>}<div className="mt-4 flex gap-3 text-sm"><button type="button" onClick={() => download(note._id)} className="font-medium hover:underline">Download</button><button type="button" onClick={() => remove(note._id)} className="text-rose-700 hover:underline">Delete</button></div></div></article>)}</div>}
        {open && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/30 p-4"><form onSubmit={submit} className="w-full max-w-lg space-y-4 rounded-lg bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Upload note</h2><button type="button" onClick={() => setOpen(false)} aria-label="Close">×</button></div><input required name="title" placeholder="Title" className="w-full rounded-md border border-slate-300 px-3 py-2" /><textarea name="description" placeholder="Description (optional)" className="min-h-24 w-full rounded-md border border-slate-300 px-3 py-2" /><input name="tags" placeholder="Tags, separated by commas" className="w-full rounded-md border border-slate-300 px-3 py-2" /><label className="block text-sm">PDF <input required type="file" accept="application/pdf" name="pdf" className="mt-1 block w-full" /></label><label className="block text-sm">Cover image (optional) <input type="file" accept="image/*" name="coverImage" className="mt-1 block w-full" /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="isPrivate" value="true" /> Keep this note private</label><div className="flex justify-end gap-3"><button type="button" onClick={() => setOpen(false)} className="px-3 py-2 text-sm">Cancel</button><button disabled={saving} className="rounded-md bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? "Uploading…" : "Upload"}</button></div></form></div>}
    </div>;
}
export default Notes;
