import { useCallback, useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { deleteNotification, getNotifications, markAllNotificationsAsRead, markNotificationAsRead } from "../services/notification.service";
import { markAllNotificationsRead, markNotificationRead, notificationsFailure, notificationsStart, notificationsSuccess, removeNotification } from "../store/slices/notificationSlice";

function Notifications() {
    const dispatch = useDispatch(); const { notifications, loading, error } = useSelector((state) => state.notifications); const [page, setPage] = useState(1); const [hasMore, setHasMore] = useState(true); const [working, setWorking] = useState({});
    const load = useCallback(async (nextPage = 1) => { dispatch(notificationsStart()); try { const response = await getNotifications(nextPage, 20); const items = response.data.data; dispatch(notificationsSuccess(nextPage === 1 ? items : [...notifications, ...items])); setPage(nextPage); setHasMore(items.length === 20); } catch { dispatch(notificationsFailure()); } }, [dispatch, notifications]);
    useEffect(() => {
        getNotifications(1, 20)
            .then((response) => { dispatch(notificationsSuccess(response.data.data)); setHasMore(response.data.data.length === 20); })
            .catch(() => dispatch(notificationsFailure()));
    }, [dispatch]);
    const action = async (id, request, reducer) => { setWorking((value) => ({ ...value, [id]: true })); try { await request(); dispatch(reducer(id)); } catch { dispatch(notificationsFailure()); } finally { setWorking((value) => ({ ...value, [id]: false })); } };
    const markAll = async () => { setWorking((value) => ({ ...value, all: true })); try { await markAllNotificationsAsRead(); dispatch(markAllNotificationsRead()); } catch { dispatch(notificationsFailure()); } finally { setWorking((value) => ({ ...value, all: false })); } };
    const hasUnread = notifications.some((item) => !item.isRead);
    return <div className="mx-auto max-w-4xl"><div className="mb-6 flex items-end justify-between gap-4"><div><h1 className="text-2xl font-bold">Inbox</h1><p className="mt-1 text-sm text-slate-500">Your recent activity and updates.</p></div>{hasUnread && <button type="button" disabled={working.all} onClick={markAll} className="text-sm font-medium text-slate-700 hover:underline disabled:opacity-50">Mark all as read</button>}</div>{error && <p className="mb-4 rounded-md border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}{loading && notifications.length === 0 ? <p className="text-sm text-slate-500">Loading inbox…</p> : notifications.length === 0 ? <div className="border-y border-slate-200 py-10 text-sm text-slate-500">No notifications yet.</div> : <div className="divide-y divide-slate-200 border-y border-slate-200">{notifications.map((item) => <article key={item._id} className={`flex items-start gap-4 p-4 ${item.isRead ? "bg-white" : "bg-sky-50/60"}`}><div className="min-w-0 flex-1"><p className="font-medium">{item.title}</p><p className="mt-1 text-sm text-slate-600">{item.message}</p><time className="mt-2 block text-xs text-slate-400">{item.createdAt && new Date(item.createdAt).toLocaleString()}</time></div><div className="flex shrink-0 gap-3 text-sm">{!item.isRead && <button type="button" disabled={working[item._id]} onClick={() => action(item._id, () => markNotificationAsRead(item._id), markNotificationRead)} className="hover:underline disabled:opacity-50">Read</button>}<button type="button" disabled={working[item._id]} onClick={() => action(item._id, () => deleteNotification(item._id), removeNotification)} className="text-rose-700 hover:underline disabled:opacity-50">Delete</button></div></article>)}</div>}{hasMore && notifications.length > 0 && <div className="pt-5 text-center"><button type="button" onClick={() => load(page + 1)} disabled={loading} className="rounded-md border border-slate-300 px-4 py-2 text-sm hover:bg-white disabled:opacity-50">Load more</button></div>}</div>;
}
export default Notifications;
