import { useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { updateAccountDetails, updateProfilePicture } from "../services/auth.service";
import { restoreUser } from "../store/slices/authSlice";

function Profile() {
    const user = useSelector((state) => state.auth.user); const dispatch = useDispatch(); const [fullName, setFullName] = useState(user?.userFullName || ""); const [bio, setBio] = useState(user?.bio || ""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const avatar = user?.profilePic?.url || user?.profilePic;
    const save = async (event) => { event.preventDefault(); setMessage(""); setError(""); try { await updateAccountDetails({ userFullName: fullName, bio }); dispatch(restoreUser({ ...user, userFullName: fullName.toUpperCase(), bio })); setMessage("Profile updated."); } catch (err) { setError(err.response?.data?.message || "Could not update profile."); } };
    const changePicture = async (event) => { const file = event.target.files?.[0]; if (!file) return; const data = new FormData(); data.append("profilePic", file); setError(""); try { const response = await updateProfilePicture(data); dispatch(restoreUser({ ...user, profilePic: response.data.data.profilePic })); setMessage("Profile picture updated."); } catch (err) { setError(err.response?.data?.message || "Could not update profile picture."); } };
    return <div className="mx-auto max-w-2xl"><h1 className="text-2xl font-bold">Profile</h1><p className="mt-1 text-sm text-slate-500">Manage the information shown with your notes and activity.</p><div className="mt-8 flex items-center gap-4 border-y border-slate-200 py-5"><span className="grid h-16 w-16 overflow-hidden rounded-full bg-slate-200 place-items-center text-xl font-semibold">{avatar ? <img src={avatar} alt="" className="h-full w-full object-cover" /> : user?.userName?.charAt(0)}</span><label className="cursor-pointer text-sm font-medium text-slate-700 hover:underline">Change profile picture<input type="file" accept="image/*" onChange={changePicture} className="hidden" /></label></div><form onSubmit={save} className="mt-6 space-y-5"><label className="block text-sm font-medium">Username<span className="mt-1 block rounded-md border border-slate-200 bg-slate-100 px-3 py-2 font-normal text-slate-500">@{user?.userName}</span></label><label className="block text-sm font-medium">Email<span className="mt-1 block rounded-md border border-slate-200 bg-slate-100 px-3 py-2 font-normal text-slate-500">{user?.email}</span></label><label className="block text-sm font-medium">Full name<input required value={fullName} onChange={(event) => setFullName(event.target.value)} className="mt-1 w-full rounded-md border border-slate-300 px-3 py-2 font-normal" /></label><label className="block text-sm font-medium">Bio<textarea value={bio} onChange={(event) => setBio(event.target.value)} className="mt-1 min-h-28 w-full rounded-md border border-slate-300 px-3 py-2 font-normal" /></label>{message && <p className="text-sm text-emerald-700">{message}</p>}{error && <p className="text-sm text-rose-700">{error}</p>}<button className="rounded-md bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Save changes</button></form></div>;
}
export default Profile;
